name = "ai-gateway"
compatibility_date = "2023-01-01"
main = "src/index.ts"
node_compat = true

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []

[[kv_namespaces]]
binding = "KV"
id = "84e40b8ef2fe48509186f540ab47e22a"

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "ai-gateway-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "ai-gateway"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []

[placement]
mode = "smart"
